# -*- coding: utf-8 -*-
"""Captcha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xQmYE6y79vEYLAgKdRLLjcovRWlai75H
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Load the image
input_image = cv2.imread('/content/car.jpeg')

# Convert the image to grayscale
gray_image = cv2.cvtColor(input_image, cv2.COLOR_BGR2GRAY)

# Apply bilateral filter to smooth the image while preserving edges
smooth_image = cv2.bilateralFilter(input_image, d=9, sigmaColor=75, sigmaSpace=75)

# Create an edge mask using adaptive thresholding
edge_mask = cv2.adaptiveThreshold(gray_image, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, blockSize=9, C=2)

# Combine the smooth image and the edge mask to create a cartoon-like effect
cartoon_image = cv2.bitwise_and(smooth_image, smooth_image, mask=edge_mask)

# Display the original and cartoon images
cv2_imshow(input_image)
cv2_imshow(smooth_image)
cv2_imshow(cartoon_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Save the cartoon image
cv2.imwrite('cartoon_image.jpg', cartoon_image)

